microsoft/mscclpp

include/mscclpp/device.hpp
include/mscclpp/gpu.hpp
include/mscclpp/gpu_utils.hpp
test/allgather_test_cpp.cu
test/mscclpp-test/allgather_test.cu
test/mscclpp-test/allreduce_test.cu

According to the [document](https://rocm.docs.amd.com/projects/HIP/en/docs-6.0.0/user_guide/hip_porting_guide.html#compiler-defines-summary), `__HIP_PLATFORM_AMD__` is effective only by definition.

Do not check value of `__HIP_PLATFORM_AMD__`

---

src/utils_internal.cc

According to https://en.cppreference.com/w/cpp/utility/program/exit
`The last destructor for thread-local objects is [sequenced-before](https://en.cppreference.com/w/cpp/language/eval_order) the first destructor for a static object.`
Change the code to avoid this case.

Fix crash in static variable deconstructor

---

include/mscclpp/fifo.hpp
include/mscclpp/proxy.hpp
include/mscclpp/proxy_channel.hpp
python/mscclpp/fifo_py.cpp
python/mscclpp/proxy_channel_py.cpp
src/proxy.cc
src/proxy_channel.cc

Related with this issue: https://github.com/microsoft/mscclpp/issues/242. The user may use more threads than the number specified in `fifo_size` to interact with the FIFO. In this case, there will be unexpected behavior.
Update the interface to let user change fifo size on their demands.

Update interface to let user change fifo size

---

include/mscclpp/proxy_channel_device.hpp

The behavior of `ProxyChannelDeviceHandle::put()` is undefined by design when each field value is given to exceed the bits limitation (such as `MSCCLPP_BITS_SIZE`). Even so, we'd better trim exceeding bits of each field value for safety, so that the invalid usage of a field does not propagate to other fields.

Mask each fields of the trigger

---

include/mscclpp/proxy_channel_device.hpp

MSCCLPP_BITS_REGMEM_HANDLE=8 limits the number registered memories for a ProxyService to 256. Many use cases, such as KV cache transfer, require registering more tensors.
This change allows registering up-to 512 memories. Note that this change uses up the slack bits remaining in the ChannelTrigger struct.

Increase MSCCLPP_BITS_REGMEM_HANDLE to 9

---

python/mscclpp/comm.py
python/mscclpp/utils.py

Obtain data_ptr and tensor_size accordingly for torch.Tensor

Allow MSCCL++ CommGroup to take PyTorch tensors in args

---

python/mscclpp/comm.py

This is needed in use cases where SimpleProxyChannel does not suffice. For example, when a single semaphore is to be used for multiple tensors or when multiple semaphores should be associated with a tensor.

Allow semaphores and memory to be registered separately in ProxyService

---

test/mscclpp-test/allreduce_test.cu

Add `__launch_bounds__` to fix perf regression issue in CI pipeline

Fix multi-node ci pipeline

---

test/deploy/perf_ndmv4.jsonl
test/mscclpp-test/allgather_test.cu
test/mscclpp-test/allreduce_test.cu
test/mscclpp-test/alltoall_test.cu
test/mscclpp-test/check_perf_result.py
test/mscclpp-test/sendrecv_test.cu

add __launch_bounds__ for mscclpp_test

add __launch_bounds__ for mscclpp_test

---

include/mscclpp/gpu.hpp
include/mscclpp/gpu_data_types.hpp
include/mscclpp/nvls_device.hpp
src/include/execution_kernel.hpp

Prevent unnecessarily including data type headers in everywhere.

Seperate headers for GPU data types 

---

include/mscclpp/core.hpp
include/mscclpp/nvls.hpp
include/mscclpp/nvls_device.hpp
python/mscclpp/comm.py
python/mscclpp/core_py.cpp
python/mscclpp/nvls_py.cpp
src/communicator.cc
src/nvls.cc

Move NVLS details from the core to a separate interface

Refactoring NVLS interfaces

---

python/mscclpp/utils.py

Use `cuda_stream` attribute of a torch stream if the stream is not an instance of the cupy stream.

Allow obtaining cuda stream handle from PyTorch stream when launching kernel

---

test/CMakeLists.txt

The new gtest version resolves a type casting issue: https://github.com/google/googletest/commit/3044657e7afa759ce875a8161cd4bff0fd2e22bc

Upgrade gtest

---

src/executor/execution_plan.cc
src/executor/executor.cc
src/include/execution_kernel.hpp
src/include/execution_plan.hpp

Bug fix: Unable to execute communication primitives with the same execution plan but varying message sizes.
Add reduce_packets OP

Cumulative Updates

---

.github/workflows/lint.yml
apps/nccl/include/nccl.h
apps/nccl/src/allgather.hpp
apps/nccl/src/allreduce.hpp
apps/nccl/src/common.hpp
apps/nccl/src/nccl.cu
cmake/AddFormatTargets.cmake

Using two scratch buffers in each peer to exchange data.

Double buffering for NCCL APIs

---

include/mscclpp/nvls_device.hpp
python/mscclpp/__init__.py
python/mscclpp/comm.py
python/mscclpp_benchmark/allreduce.cu
python/mscclpp_benchmark/allreduce_bench.py
python/mscclpp_benchmark/mscclpp_op.py

Also fixes bugs in MscclppAllReduce6
Below is the performance when the algorithm is fixed to MscclppAllReduce6 on 8 H100 GPUs connected with NVLink using CUDA 12.2.
Float16:
+-------------+-----------+--------------+-------------+----------------+-------------------+------------------+----------+
| Size (fp16) | Time (us) | AlgBW (GB/s) | Correctness | NCCL Time (us) | NCCL AlgBW (GB/s) | NCCL Correctness | Speed Up |
+-------------+-----------+--------------+-------------+----------------+-------------------+------------------+----------+
|   2.0 KiB   |   11.15   |     0.18     |     PASS    |     13.82      |        0.15       |       PASS       |   1.24   |
|   4.0 KiB   |   11.15   |     0.37     |     PASS    |     14.74      |        0.28       |       PASS       |   1.32   |
| …

Auto-tune vector sizes for NVLS allreduce6

---

apps/nccl/src/nccl.cu
include/mscclpp/executor.hpp
python/mscclpp/executor_py.cpp
python/test/executor_test.py
python/test/test_mscclpp.py
src/executor/execution_plan.cc
src/executor/executor.cc
src/include/execution_plan.hpp
test/execution-files/allreduce.json
test/execution-files/allreduce_packet.json
test/executor_test.cc
test/mp_unit/executor_tests.cc

tune threads per block for mscclpp executor

Tune threads per block for mscclpp executor

---

src/context.cc
src/include/context.hpp

Create the context stream only when needed.

Lazily create the context stream

---

src/executor/execution_plan.cc

The offset was not differentiating between the buffer types, causing the offset to be incorrect when the buffer type was not `SCRATCH`.

Fixing Bug Const Offset in Execution Plan

---

src/executor/executor.cc

Fix lightLoadExecutionPlan issue.
An execution context many have multi device execution plans. These plans share the channel connections which are constructed before.
A deviceExecutionPlanKey is introduced to identify these plans. We can get the current device execution plan key via:
`contexts.currentDevicePlan`

Fix light load bug

---

python/mscclpp/comm.py
python/mscclpp_benchmark/allreduce_bench.py

Enable 1GB message size for NVLS transport in mscclpp_benchmark

Fix mscclpp_benchmark

---

apps/nccl/src/nccl.cu
include/mscclpp/executor.hpp
python/mscclpp/executor_py.cpp
python/test/executor_test.py
python/test/test_mscclpp.py
src/executor/execution_plan.cc
src/include/execution_plan.hpp
test/execution-files/allreduce.json
test/execution-files/allreduce_nvls.json
test/execution-files/allreduce_packet.json
test/execution-files/sendrecv.json
test/execution-files/sendrecv_packet.json
test/executor_test.cc
test/mp_unit/executor_tests.cc

The way to run nccl-test over mscclpp:
mpirun -np 8 --bind-to numa --allow-run-as-root -x LD_PRELOAD=$(pwd)/build/apps/nccl/libmscclpp_nccl.so -x NCCL_DEBUG=WARN  -x MSCCLPP_EXECUTION_PLAN_DIR=/execution-files /root/nccl-tests/build/all_reduce_perf   -b 1K -e 1G -f 2 -d half -G 20 -w 10 -n 20

Select algo according to json config

---

README.md
docs/design/design.md
docs/getting-started/tutorials/initialization.md
docs/getting-started/tutorials/python-api.md
include/mscclpp/proxy_channel.hpp
include/mscclpp/proxy_channel_device.hpp
python/mscclpp/__init__.py
python/mscclpp/comm.py
python/mscclpp/proxy_channel_py.cpp
python/mscclpp_benchmark/allreduce.cu
python/test/proxy_channel_test.cu
python/test/test_mscclpp.py
src/executor/executor.cc
src/include/execution_common.hpp
src/include/execution_kernel.hpp
src/proxy_channel.cc
src/semaphore.cc
test/allgather_test_cpp.cu
test/mp_unit/mp_unit_tests.hpp
test/mp_unit/proxy_channel_tests.cu
test/mscclpp-test/allgather_test.cu
test/mscclpp-test/allreduce_test.cu
test/mscclpp-test/alltoall_test.cu
test/mscclpp-test/common.cc
test/mscclpp-test/common.hpp

* Renamed `ProxyChannel` -> `BaseProxyChannel` and `SimpleProxyChannel` -> `ProxyChannel`. It makes the interface more consistent by defining channels to be associated with a certain src/dst memory region: `ProxyChannel` as "sema + src/dst + fifo" and `SmChannel` as "sema + src/dst". BaseProxyChannel is not associated with any memory regions, as "sema + fifo".
* `ProxyChannelDeviceHandle` now inherits from `BaseProxyChannelDeviceHandle`, instead of having one as a member.

Revised ProxyChannel interfaces

---

apps/nccl/src/broadcast.hpp
apps/nccl/src/nccl.cu

Encountered a hang with rccl-test's ncclBcast runs. In rccl-test with ncclBcast, the buffer changes only for the root-gpu b/w test runs. So, the channel key changes only for the root gpu and remains the same for the other gpus. So, the root gpu starts to create a new sm channel while the other gpus do not create new sm channels. Hence, a hang occurs.
To fix this, we have to use copy-based implementation. This is the simplest copy-based implementation. Uses a static channel key with sm channels created using scratch buffer as the remote memories.

Scratch buffer copy-based implementation of ncclBcast / ncclBroadcast

---

apps/nccl/src/allreduce.hpp

Running kernel allreduce8 across 64 vGPUs (in CPX mode) revealed a synchronization bug. The PR addresses it by ensuring that signals are only issued after all threads in the block have issued their writes to guarantee correct ordering between data writes and signal writes.

Fix synchronization in allreduce8 kernel

---

.azure-pipelines/integration-test.yml
.azure-pipelines/ut.yml
test/deploy/deploy.sh

Move pipeline to official org. Unify all pipelines

[Cherry-pick] Move pipeline to official org (#406)

---

src/registered_memory.cc

* Updated `RegisteredMemory::Impl::Impl(const std::vector<char>& serialization)` to use both minimum and recommended granularities for memory address reservation and mapping. This will resolve the cuMemMap error

Resolve cuMemMap error

---

python/mscclpp/language/ir.py

`nop` instruction is only for synchronization within the same threadblock. Cross threadblock synchronization is handled by `barrier` instruction. So insert `nop` only if the dependency is within the same threadblock.

remove unnecessary sync

---

src/gpu_utils.cc
src/registered_memory.cc

This pull request includes changes to improve memory management in GPU-related functions by ensuring proper release of memory handles. 
Fix #470

Fix memory OOM issue

---

apps/nccl/src/allgather.hpp
apps/nccl/src/nccl.cu
include/mscclpp/env.hpp
src/debug.cc
src/env.cpp
src/include/debug.h

Enhancements to all-gather operation, a temporary solution to fix the memory overhead when integrating msccl++ with pytorch.
This solution will not register input/output buffer to msccl++, so the temp output buffer for allgather could be reused by torch automatically.
* Introduced a new `allgather8` kernel function in `apps/nccl/src/allgather.hpp` to handle larger data sizes more efficiently. This includes double buffering to hide synchronization overhead and support for both in-place and out-of-place operations.
* Modified the `allgather` function to decide between `allgather6` and `allgather8` based on data size and platform, improving performance for large data sizes.
Configuration and environment improvements:
* Added a new environment variable `MSCCLPP_DISABLE_CHANNEL_CACHE` to …

Update allgather fallback algo

---

docs/getting-started/quickstart.md
include/mscclpp/gpu.hpp
include/mscclpp/gpu_utils.hpp
src/gpu_utils.cc
src/include/registered_memory.hpp
src/registered_memory.cc

Remove the requirement for `CU_DEVICE_ATTRIBUTE_HANDLE_TYPE_FABRIC_SUPPORTED` for NVLS support.
Fix #487

Remove the requirement for `CU_DEVICE_ATTRIBUTE_HANDLE_TYPE_FABRIC_SUPPORTED` for NVLS support

---

.github/workflows/lint.yml
include/mscclpp/gpu_utils.hpp
pyproject.toml
python/mscclpp/CMakeLists.txt
python/mscclpp/gpu_utils_py.cpp
src/executor/execution_plan.cc
src/gpu_utils.cc
src/nvls.cc
src/registered_memory.cc

For mscclpp, to use nvls we require the buffer is allocated by mscclpp::GpuBuffer. Due to cupy doesn't support bfloat16 yet, we export the raw buffer to dlpack format.
User can use this feature to create buffer with type supported by pytorch
```python
buffer = RawGpuBuffer(1024 * 2) # 2 for bfloat16
dl_pack = buffer.to_dlpack(str(torch.bfloat16))
tensor = torch.utils.dlpack.from_dlpack(dl_pack)
```

Export mscclpp GpuBuffer to dlpack format

---

src/include/registered_memory.hpp
src/registered_memory.cc

Fix the virtual address mapping issue of cuMemMap by using the size of device memory allocation instead of user buffer size

Fix the virtual address mapping issue of cuMemMap in fallback code

---

CMakeLists.txt
include/mscclpp/atomic_device.hpp
include/mscclpp/concurrency_device.hpp
include/mscclpp/fifo_device.hpp
include/mscclpp/poll_device.hpp
include/mscclpp/semaphore_device.hpp
test/unit/compile_tests.cu

Remove __assert_fail for release build. This will reduce the number of PTX instructions inside the loop. Also Trying to resolve this issue reported in #497. Reduce the number of PTX instructions from 8 to 6. 
8 ranks signal/wait will reduce from 3.2us->2.8us on NDv5
Also NDEBUG flag is confused here, sometime it will not be set. Use customized flag for debug build.
Here is current PTX:
```
ld.u64  %rd12, [%rd2+-24];
mov.u64         %rd13, %rd12;
mov.u64         %rd11, %rd13;
ld.acquire.sys.b64 %rd10,[%rd11];
setp.lt.u64     %p1, %rd10, %rd3;
@%p1 bra        $L__BB2_1;
```
If we change to `asm volatile("ld.global.acquire.sys.b64 %0, [%1];" : "=l"(flag) : "l"(flag_addr));` will reduce to 4 instructions. We can get 2.1 us for 8 ranks signal/wait
```
ld.u64  %rd9, [%rd1+-24]; …
```

Improve signal/wait performance and fix barrier issue

---

include/mscclpp/concurrency_device.hpp
include/mscclpp/fifo_device.hpp
include/mscclpp/memory_channel_device.hpp
include/mscclpp/semaphore_device.hpp
python/mscclpp_benchmark/allreduce.cu
test/deploy/perf_ndmv4.jsonl

1. use `fence+relaxed` to replace `release` for fifo. `fence+relax` is more efficient on A100
2. Update the deviceSyncer. Previous one cannot handle threadBlock number change correctly. Use three counters to solve this issue. Reset previous counter before sync on current counter.
3. Introduce relaxedWait which can be used with relaxedSignal for case doesn't need guarantee the memory visibility

Fix performance issue introduced in PR: 499

---

include/mscclpp/env.hpp
include/mscclpp/gpu.hpp
include/mscclpp/gpu_utils.hpp
src/env.cpp
src/gpu_utils.cc
src/nvls.cc
src/registered_memory.cc
test/nvls_test.cu

Mitigate this issue: #496, for now `ibv_reg_dmabuf_mr` is not supported by Azure vm. Add this flag to force to use cudaMalloc for memory allocation and disable nvls feature

Add flag to disable nvls

---

apps/nccl/src/allreduce.hpp
apps/nccl/src/nccl.cu

* Pass the op type as a template parameter
* Use the all-pairs algorithm for ~10KB
* Don't write channel handles on the shared memory for small sizes
* A reduction bug fix & cleanup

Optimized allreduce fallback for ~10KB sizes

---

include/mscclpp/packet_device.hpp
include/mscclpp/port_channel_device.hpp

By using implicit constructors, the compiler doesn't need to dynamically initialize the instances.

Use implicit ctors for default device ctors

---

apps/nccl/src/allreduce.hpp
apps/nccl/src/nccl.cu

`allreduce7` and `allreduceAllpairs` kernels were updating the LL protocol flag on the host side. So, it was not properly captured in graph mode. This PR fixes the issue by updating the flag in the kernels.

apps/nccl: fix a bug in allreduce kernels for graph mode

---

include/mscclpp/assert_device.hpp
include/mscclpp/memory_channel_device.hpp
include/mscclpp/poll_device.hpp
python/test/nvls_test.cu

* Fixed a bug that external `assert()`s may not be compiled with mscclpp headers
* Use a macro assert instead of a function

Fix device assert

---

CMakeLists.txt

`MSCCLPP_GPU_ARCHS` allows specifying GPU architectures with delimiters (comma, space, or semicolon).

Add a CMake option `MSCCLPP_GPU_ARCHS`

---

python/test/test_mscclpp.py
src/connection.cc

When we create the thread to receive messages in the Ethernet Connection, it resets the Device ID, causing faults in the Ethernet Connection unit tests. 
This PR aims to properly set up the device when the thread is created.

Properly setting up the device in Ethernet Connection

---

CMakeLists.txt
pyproject.toml
python/mscclpp/CMakeLists.txt

* Let CMake read version numbers from the `VERSION` file.
* Upgrade dlpack and drop `CMAKE_POLICY_VERSION_MINIMUM`.
* Do not install dlpack.
* Add license files in the wheel and exclude `*.cpp` files.

Fix build processes

---

include/mscclpp/concurrency_device.hpp

Fix the bug, make sure a thread will be wake up if semaphore be released.
This pull request includes a modification to the `DeviceSemaphore` struct in the `concurrency_device.hpp` file, specifically in the `acquire` method. The change refines the logic for acquiring a semaphore by adjusting the condition used to handle contention scenarios.

DeviceSemaphore  fix

---

include/mscclpp/concurrency_device.hpp
test/mscclpp-test/alltoall_test.cu

Implement single node all2all via MSCCL++ C++API
perf kernel 3:
```
size         count     time   algbw   busbw  #wrong     time   algbw   busbw  #wrong
1048576         32768                                     23.41   44.78   39.19      0
2097152         65536                                     23.95   87.56   76.61      0
4194304        131072                                     27.50  152.51  133.45      0
8388608        262144                                     35.14  238.73  208.89      0
16777216        524288                                     57.54  291.55  255.11      0
33554432       1048576                                     109.7  305.81  267.59      0
67108864       2097152                                     212.3  316.07  276.56      0
134217728       4194304 …
```

all2all implementation

---

src/executor/executor.cc

In cases where we have circular channel creation, such as:
creating channel 0 <-> 1
creating channel 1 <-> 2
creating channel 2 <-> 3
creating channel 3 <-> 0
creating channel 0 <-> 3
creating channel 1 <-> 0
creating channel 2 <-> 1
creating channel 3 <-> 2
This setup can result in a deadlock during the first channel creation for each rank. The current code requires sharing the semaphore for the first channel before moving on, which leads to the following sequence:
creating channel 0 <-> 1
creating channel 1 <-> 2
creating channel 2 <-> 3
creating channel 3 <-> 0
<-- HANG ISSUE -->
The process hangs because, for example, rank 0 will only share the semaphore with rank 3 after receiving it from rank 1. However, rank 1 is waiting for a semaphore from rank 2, rank 2 is waiting for one from …

Fix deadlock in Executor channel setup

---

docs/guide/mscclpp-dsl.md
python/mscclpp/language/channel.py
python/mscclpp/language/internal/operations.py
python/mscclpp/language/rank.py
python/mscclpp/language/tests/multi_node/allgather_tbg.py
python/mscclpp/language/tests/single_node/allgather_tbg.py
python/mscclpp/language/tests/unit_tests/tbg/reduce_send_test.py
python/mscclpp/language/tests/unit_tests/tbg/tbg_copy_test.py
python/mscclpp/language/tests/unit_tests/tbg/tbg_reduce_fuse_test.py
python/mscclpp/language/tests/unit_tests/tbg/tbg_reduce_send_test.py
python/mscclpp/language/tests/unit_tests/tbg/tbg_reduce_test.py
python/mscclpp/language/thread_block_group.py
src/executor/execution_plan.cc
src/include/execution_plan.hpp

Supporting the creation of a group of thread block to perform some operation.

Thread Block Group DSL

---

src/debug.cc

Fix: #622, using std::recursive_mutex to allow acquiring `lock` reclusively in the same thread

Fix hang issue in logging submodule 

---

apps/nccl/src/allgather.cu
apps/nccl/src/allgather.hpp
apps/nccl/src/allreduce.cu
apps/nccl/src/allreduce.hpp
apps/nccl/src/nccl.cu

Reduce memory footprint for allreduce8 and allgather6
Remove libLoadSucceed check for group start

Reduce memory footprint for allreduce8 and allgather6
