microsoft/mscclpp

- .azure-pipelines/multi-nodes-test.yml
- .azure-pipelines/ut.yml
- .github/workflows/ut-backup.yml
- python/CMakeLists.txt
Fix #216
Remove `make pylib-copy`
> remove make pylib-copy command

- include/mscclpp/nvls_device.hpp
- python/mscclpp/comm.py
- src/connection.cc
- test/nvls_test.cu
* Do not compile nvls_test with ROCm
* Fix multi-node tests
> Fix NVLS support

- python/mscclpp_benchmark/allreduce_bench.py
> Fix multi-nodes test failure

- include/mscclpp/core.hpp
- include/mscclpp/nvls_device.hpp
- python/mscclpp_benchmark/allreduce.cu
- python/test/nvls_test.cu
- src/nvls_connection.cc
And change NVLS multimem instructions to static functions
> Allow binding allocated memory to NVLS multicast pointer

- src/connection.cc
- src/endpoint.cc
Fix bug, resolve multi-nodes test failure issue.
> Resolve multi-nodes test failure issue

- src/utils_internal.cc
Change sprintf to snprintf to avoid potential security issue
> Fix security issue

- python/mscclpp_benchmark/allreduce.cu
Drop superfluous __threadfence_system()
> Simplify/improve barrier in AllReduce6

- include/mscclpp/packet_device.hpp
> Support to write packets via uint2

- src/executor/execution_plan.cc
- src/include/execution_common.hpp
- src/include/execution_kernel.hpp
- test/execution-files/sendrecv.json
- tools/npkit/npkit_trace_generator.py
Add Flush, PutWithSignal, PutWithFlushAndSignal operation
> Add proxy channel related operations

- .azure-pipelines/integration-test-rocm.yml
Change algo repo name from azure-mscclpp  to msccl-users
> Fix algo repo name

- docker/base-dev-x.dockerfile
- docker/base-x-rocm.dockerfile
- docker/base-x.dockerfile
- docker/build.sh
Update docker image for cuda12.4
Image pushed to registry
> Update docker image for cuda12.4

- README.md
Small fix to update quickstart link
> [docs] fix quickstart link

- python/test/executor_test.py
- python/test/executor_test_verifier.cu
Add kernels to fill and test data for correctness test in executor_test.py.
> Add kernel-based verification for executor_test

- .azure-pipelines/integration-test.yml
- .azure-pipelines/nccl-api-test.yaml
- .azure-pipelines/ut.yml
- test/deploy/deploy.sh
Move pipeline to official org. Unify all pipelines
> Move pipeline to official org

- apps/nccl/src/broadcast.hpp
- apps/nccl/src/nccl.cu
A simple broadcast using scratch buffer and option to use an executor.
> Add ncclBcast / ncclBroadcast support

- CMakeLists.txt
- apps/nccl/src/broadcast.hpp
- apps/nccl/src/nccl.cu
- cmake/AddFormatTargets.cmake
- include/mscclpp/proxy_channel_device.hpp
* Comply with [CMP0165](https://cmake.org/cmake/help/latest/policy/CMP0165.html)
* Tackle other warnings during build
> Tackle build warnings

- .azure-pipelines/ut.yml
- apps/nccl/src/nccl.cu
- include/mscclpp/env.hpp
- pyproject.toml
- python/mscclpp/__init__.py
- python/mscclpp/core_py.cpp
- python/mscclpp/env_py.cpp
- python/test/executor_test.py
- python/test/test_mscclpp.py
- src/CMakeLists.txt
- src/bootstrap/socket.cc
- src/debug.cc
- src/env.cpp
- src/ib.cc
- src/utils_internal.cc
- test/executor_test.cc
- test/mp_unit/executor_tests.cc
- test/mp_unit/mp_unit_tests.hpp
- tools/npkit/build_and_run_npkit.sh
* Add `Env` class that manages all runtime environments.
* Changed `NPKIT_DUMP_DIR` to `MSCCLPP_NPKIT_DUMP_DIR`.
> Manage runtime environments

- docs/design/mscclpp-dsl.md
- docs/getting-started/quickstart.md
* Fix minor typos and errors in documentation
> Fix minor typos and errors in documentation

- apps/nccl/src/nccl.cu
If `mscclppDisableChannelCache` set to true, we need to keep every channel information avoid the channel info in GPU side be released.
> Fix correctness issue when mscclppDisableChannelCache set to true

- include/mscclpp/gpu_utils.hpp
- python/mscclpp/gpu_utils_py.cpp
- src/gpu_utils.cc
* Fix typos in type name
* Make it work without current context set
> DLPack fixes

- python/mscclpp/language/internal/gpu.py
- python/mscclpp/language/internal/operations.py
- python/mscclpp/language/internal/optmizer.py
- python/mscclpp/language/internal/threadblock.py
- python/mscclpp/language/internal/types.py
- python/mscclpp/language/program.py
- python/mscclpp/language/rank.py
- python/mscclpp/language/tests/unit_tests/semaphore.py
Introduces an asynchronous synchronization mechanism for threads within the same rank.
> Supporting Semaphore operations at DSL

- src/include/execution_kernel.hpp
> fix rocm build

- apps/nccl/src/allreduce.hpp
- apps/nccl/src/nccl.cu
Fix NVLS correctness issue when dytpe != fp16
> Fix NVLS correctness issue
